cp root/templates/subSilver/images/lang_english/icon_hidden.png ../../../templates/subSilver/images/lang_english/icon_hidden.png
cp root/templates/subSilver/images/lang_english/icon_offline.png ../../../templates/subSilver/images/lang_english/icon_offline.png
cp root/templates/subSilver/images/lang_english/icon_online.png ../../../templates/subSilver/images/lang_english/icon_online.png
cp ../../../language/lang_english/lang_admin.php backups/language/lang_english/lang_admin.php.txt
cp processed/language/lang_english/lang_admin.php.txt ../../../language/lang_english/lang_admin.php
cp ../../../language/lang_russian/lang_admin.php backups/language/lang_russian/lang_admin.php.txt
cp processed/language/lang_russian/lang_admin.php.txt ../../../language/lang_russian/lang_admin.php
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
cp ../../../language/lang_russian/lang_main.php backups/language/lang_russian/lang_main.php.txt
cp processed/language/lang_russian/lang_main.php.txt ../../../language/lang_russian/lang_main.php
cp ../../../viewtopic.php backups/viewtopic.php.txt
cp processed/viewtopic.php.txt ../../../viewtopic.php
cp ../../../memberlist.php backups/memberlist.php.txt
cp processed/memberlist.php.txt ../../../memberlist.php
cp ../../../includes/usercp_viewprofile.php backups/includes/usercp_viewprofile.php.txt
cp processed/includes/usercp_viewprofile.php.txt ../../../includes/usercp_viewprofile.php
cp ../../../groupcp.php backups/groupcp.php.txt
cp processed/groupcp.php.txt ../../../groupcp.php
cp ../../../privmsg.php backups/privmsg.php.txt
cp processed/privmsg.php.txt ../../../privmsg.php
cp ../../../includes/page_header.php backups/includes/page_header.php.txt
cp processed/includes/page_header.php.txt ../../../includes/page_header.php
cp ../../../admin/admin_board.php backups/admin/admin_board.php.txt
cp processed/admin/admin_board.php.txt ../../../admin/admin_board.php
cp ../../../admin/admin_styles.php backups/admin/admin_styles.php.txt
cp processed/admin/admin_styles.php.txt ../../../admin/admin_styles.php
cp ../../../templates/subSilver/viewtopic_body.tpl backups/templates/subSilver/viewtopic_body.tpl.txt
cp processed/templates/subSilver/viewtopic_body.tpl.txt ../../../templates/subSilver/viewtopic_body.tpl
cp ../../../templates/subSilver/memberlist_body.tpl backups/templates/subSilver/memberlist_body.tpl.txt
cp processed/templates/subSilver/memberlist_body.tpl.txt ../../../templates/subSilver/memberlist_body.tpl
cp ../../../templates/subSilver/profile_view_body.tpl backups/templates/subSilver/profile_view_body.tpl.txt
cp processed/templates/subSilver/profile_view_body.tpl.txt ../../../templates/subSilver/profile_view_body.tpl
cp ../../../templates/subSilver/groupcp_info_body.tpl backups/templates/subSilver/groupcp_info_body.tpl.txt
cp processed/templates/subSilver/groupcp_info_body.tpl.txt ../../../templates/subSilver/groupcp_info_body.tpl
cp ../../../templates/subSilver/groupcp_pending_info.tpl backups/templates/subSilver/groupcp_pending_info.tpl.txt
cp processed/templates/subSilver/groupcp_pending_info.tpl.txt ../../../templates/subSilver/groupcp_pending_info.tpl
cp ../../../templates/subSilver/privmsgs_read_body.tpl backups/templates/subSilver/privmsgs_read_body.tpl.txt
cp processed/templates/subSilver/privmsgs_read_body.tpl.txt ../../../templates/subSilver/privmsgs_read_body.tpl
cp ../../../templates/subSilver/admin/board_config_body.tpl backups/templates/subSilver/admin/board_config_body.tpl.txt
cp processed/templates/subSilver/admin/board_config_body.tpl.txt ../../../templates/subSilver/admin/board_config_body.tpl
cp ../../../templates/subSilver/admin/styles_edit_body.tpl backups/templates/subSilver/admin/styles_edit_body.tpl.txt
cp processed/templates/subSilver/admin/styles_edit_body.tpl.txt ../../../templates/subSilver/admin/styles_edit_body.tpl
cp ../../../templates/subSilver/overall_header.tpl backups/templates/subSilver/overall_header.tpl.txt
cp processed/templates/subSilver/overall_header.tpl.txt ../../../templates/subSilver/overall_header.tpl
cp ../../../templates/subSilver/subSilver.css backups/templates/subSilver/subSilver.css.txt
cp processed/templates/subSilver/subSilver.css.txt ../../../templates/subSilver/subSilver.css
cp ../../../templates/subSilver/subSilver.cfg backups/templates/subSilver/subSilver.cfg.txt
cp processed/templates/subSilver/subSilver.cfg.txt ../../../templates/subSilver/subSilver.cfg
