copy root\templates\subSilver\images\lang_english\icon_hidden.png ..\..\..\templates\subSilver\images\lang_english\icon_hidden.png
copy root\templates\subSilver\images\lang_english\icon_offline.png ..\..\..\templates\subSilver\images\lang_english\icon_offline.png
copy root\templates\subSilver\images\lang_english\icon_online.png ..\..\..\templates\subSilver\images\lang_english\icon_online.png
copy ..\..\..\language\lang_english\lang_admin.php backups\language\lang_english\lang_admin.php.txt
copy processed\language\lang_english\lang_admin.php.txt ..\..\..\language\lang_english\lang_admin.php
copy ..\..\..\language\lang_russian\lang_admin.php backups\language\lang_russian\lang_admin.php.txt
copy processed\language\lang_russian\lang_admin.php.txt ..\..\..\language\lang_russian\lang_admin.php
copy ..\..\..\language\lang_english\lang_main.php backups\language\lang_english\lang_main.php.txt
copy processed\language\lang_english\lang_main.php.txt ..\..\..\language\lang_english\lang_main.php
copy ..\..\..\language\lang_russian\lang_main.php backups\language\lang_russian\lang_main.php.txt
copy processed\language\lang_russian\lang_main.php.txt ..\..\..\language\lang_russian\lang_main.php
copy ..\..\..\viewtopic.php backups\viewtopic.php.txt
copy processed\viewtopic.php.txt ..\..\..\viewtopic.php
copy ..\..\..\memberlist.php backups\memberlist.php.txt
copy processed\memberlist.php.txt ..\..\..\memberlist.php
copy ..\..\..\includes\usercp_viewprofile.php backups\includes\usercp_viewprofile.php.txt
copy processed\includes\usercp_viewprofile.php.txt ..\..\..\includes\usercp_viewprofile.php
copy ..\..\..\groupcp.php backups\groupcp.php.txt
copy processed\groupcp.php.txt ..\..\..\groupcp.php
copy ..\..\..\privmsg.php backups\privmsg.php.txt
copy processed\privmsg.php.txt ..\..\..\privmsg.php
copy ..\..\..\includes\page_header.php backups\includes\page_header.php.txt
copy processed\includes\page_header.php.txt ..\..\..\includes\page_header.php
copy ..\..\..\admin\admin_board.php backups\admin\admin_board.php.txt
copy processed\admin\admin_board.php.txt ..\..\..\admin\admin_board.php
copy ..\..\..\admin\admin_styles.php backups\admin\admin_styles.php.txt
copy processed\admin\admin_styles.php.txt ..\..\..\admin\admin_styles.php
copy ..\..\..\templates\subSilver\viewtopic_body.tpl backups\templates\subSilver\viewtopic_body.tpl.txt
copy processed\templates\subSilver\viewtopic_body.tpl.txt ..\..\..\templates\subSilver\viewtopic_body.tpl
copy ..\..\..\templates\subSilver\memberlist_body.tpl backups\templates\subSilver\memberlist_body.tpl.txt
copy processed\templates\subSilver\memberlist_body.tpl.txt ..\..\..\templates\subSilver\memberlist_body.tpl
copy ..\..\..\templates\subSilver\profile_view_body.tpl backups\templates\subSilver\profile_view_body.tpl.txt
copy processed\templates\subSilver\profile_view_body.tpl.txt ..\..\..\templates\subSilver\profile_view_body.tpl
copy ..\..\..\templates\subSilver\groupcp_info_body.tpl backups\templates\subSilver\groupcp_info_body.tpl.txt
copy processed\templates\subSilver\groupcp_info_body.tpl.txt ..\..\..\templates\subSilver\groupcp_info_body.tpl
copy ..\..\..\templates\subSilver\groupcp_pending_info.tpl backups\templates\subSilver\groupcp_pending_info.tpl.txt
copy processed\templates\subSilver\groupcp_pending_info.tpl.txt ..\..\..\templates\subSilver\groupcp_pending_info.tpl
copy ..\..\..\templates\subSilver\privmsgs_read_body.tpl backups\templates\subSilver\privmsgs_read_body.tpl.txt
copy processed\templates\subSilver\privmsgs_read_body.tpl.txt ..\..\..\templates\subSilver\privmsgs_read_body.tpl
copy ..\..\..\templates\subSilver\admin\board_config_body.tpl backups\templates\subSilver\admin\board_config_body.tpl.txt
copy processed\templates\subSilver\admin\board_config_body.tpl.txt ..\..\..\templates\subSilver\admin\board_config_body.tpl
copy ..\..\..\templates\subSilver\admin\styles_edit_body.tpl backups\templates\subSilver\admin\styles_edit_body.tpl.txt
copy processed\templates\subSilver\admin\styles_edit_body.tpl.txt ..\..\..\templates\subSilver\admin\styles_edit_body.tpl
copy ..\..\..\templates\subSilver\overall_header.tpl backups\templates\subSilver\overall_header.tpl.txt
copy processed\templates\subSilver\overall_header.tpl.txt ..\..\..\templates\subSilver\overall_header.tpl
copy ..\..\..\templates\subSilver\subSilver.css backups\templates\subSilver\subSilver.css.txt
copy processed\templates\subSilver\subSilver.css.txt ..\..\..\templates\subSilver\subSilver.css
copy ..\..\..\templates\subSilver\subSilver.cfg backups\templates\subSilver\subSilver.cfg.txt
copy processed\templates\subSilver\subSilver.cfg.txt ..\..\..\templates\subSilver\subSilver.cfg
