copy attachment_mod\download.php ..\..\..\download.php
copy attachment_mod\uacp.php ..\..\..\uacp.php
copy attachment_mod\attach_rules.php ..\..\..\attach_rules.php
copy attachment_mod\admin\admin_attach_cp.php ..\..\..\admin\admin_attach_cp.php
copy attachment_mod\admin\admin_attachments.php ..\..\..\admin\admin_attachments.php
copy attachment_mod\admin\admin_extensions.php ..\..\..\admin\admin_extensions.php
copy attachment_mod\attach_mod\attachment_mod.php ..\..\..\attach_mod\attachment_mod.php
copy attachment_mod\attach_mod\displaying.php ..\..\..\attach_mod\displaying.php
copy attachment_mod\attach_mod\index.htm ..\..\..\attach_mod\index.htm
copy attachment_mod\attach_mod\pm_attachments.php ..\..\..\attach_mod\pm_attachments.php
copy attachment_mod\attach_mod\posting_attachments.php ..\..\..\attach_mod\posting_attachments.php
copy attachment_mod\attach_mod\includes\constants.php ..\..\..\attach_mod\includes\constants.php
copy attachment_mod\attach_mod\includes\functions_admin.php ..\..\..\attach_mod\includes\functions_admin.php
copy attachment_mod\attach_mod\includes\functions_attach.php ..\..\..\attach_mod\includes\functions_attach.php
copy attachment_mod\attach_mod\includes\functions_delete.php ..\..\..\attach_mod\includes\functions_delete.php
copy attachment_mod\attach_mod\includes\functions_filetypes.php ..\..\..\attach_mod\includes\functions_filetypes.php
copy attachment_mod\attach_mod\includes\functions_includes.php ..\..\..\attach_mod\includes\functions_includes.php
copy attachment_mod\attach_mod\includes\functions_selects.php ..\..\..\attach_mod\includes\functions_selects.php
copy attachment_mod\attach_mod\includes\functions_thumbs.php ..\..\..\attach_mod\includes\functions_thumbs.php
copy attachment_mod\attach_mod\includes\index.htm ..\..\..\attach_mod\includes\index.htm
copy attachment_mod\files\index.php ..\..\..\files\index.php
copy attachment_mod\images\icon_clip.gif ..\..\..\images\icon_clip.gif
copy attachment_mod\images\icon_disk.gif ..\..\..\images\icon_disk.gif
copy attachment_mod\images\icon_disk_gray.gif ..\..\..\images\icon_disk_gray.gif
copy attachment_mod\templates\subSilver\add_attachment_body.tpl ..\..\..\templates\subSilver\add_attachment_body.tpl
copy attachment_mod\templates\subSilver\posted_attachments_body.tpl ..\..\..\templates\subSilver\posted_attachments_body.tpl
copy attachment_mod\templates\subSilver\posting_attach_body.tpl ..\..\..\templates\subSilver\posting_attach_body.tpl
copy attachment_mod\templates\subSilver\posting_attach_rules.tpl ..\..\..\templates\subSilver\posting_attach_rules.tpl
copy attachment_mod\templates\subSilver\uacp_body.tpl ..\..\..\templates\subSilver\uacp_body.tpl
copy attachment_mod\templates\subSilver\viewtopic_attach_body.tpl ..\..\..\templates\subSilver\viewtopic_attach_body.tpl
copy attachment_mod\templates\subSilver\admin\attach_cat_body.tpl ..\..\..\templates\subSilver\admin\attach_cat_body.tpl
copy attachment_mod\templates\subSilver\admin\attach_cp_attachments.tpl ..\..\..\templates\subSilver\admin\attach_cp_attachments.tpl
copy attachment_mod\templates\subSilver\admin\attach_cp_body.tpl ..\..\..\templates\subSilver\admin\attach_cp_body.tpl
copy attachment_mod\templates\subSilver\admin\attach_cp_search.tpl ..\..\..\templates\subSilver\admin\attach_cp_search.tpl
copy attachment_mod\templates\subSilver\admin\attach_cp_user.tpl ..\..\..\templates\subSilver\admin\attach_cp_user.tpl
copy attachment_mod\templates\subSilver\admin\attach_extension_groups.tpl ..\..\..\templates\subSilver\admin\attach_extension_groups.tpl
copy attachment_mod\templates\subSilver\admin\attach_extensions.tpl ..\..\..\templates\subSilver\admin\attach_extensions.tpl
copy attachment_mod\templates\subSilver\admin\attach_forbidden_extensions.tpl ..\..\..\templates\subSilver\admin\attach_forbidden_extensions.tpl
copy attachment_mod\templates\subSilver\admin\attach_manage_body.tpl ..\..\..\templates\subSilver\admin\attach_manage_body.tpl
copy attachment_mod\templates\subSilver\admin\attach_quota_body.tpl ..\..\..\templates\subSilver\admin\attach_quota_body.tpl
copy attachment_mod\templates\subSilver\admin\attach_shadow.tpl ..\..\..\templates\subSilver\admin\attach_shadow.tpl
copy attachment_mod\templates\subSilver\admin\extension_groups_permissions.tpl ..\..\..\templates\subSilver\admin\extension_groups_permissions.tpl
copy attachment_mod\language\lang_english\lang_admin_attach.php ..\..\..\language\lang_english\lang_admin_attach.php
copy attachment_mod\language\lang_english\lang_admin_attach.php ..\..\..\language\lang_russian\lang_admin_attach.php
copy attachment_mod\language\lang_english\lang_faq_attach.php ..\..\..\language\lang_english\lang_faq_attach.php
copy attachment_mod\language\lang_english\lang_faq_attach.php ..\..\..\language\lang_russian\lang_faq_attach.php
copy attachment_mod\language\lang_english\lang_main_attach.php ..\..\..\language\lang_english\lang_main_attach.php
copy attachment_mod\language\lang_english\lang_main_attach.php ..\..\..\language\lang_russian\lang_main_attach.php
copy attachment_mod\install\install.php ..\..\..\install\install.php
copy attachment_mod\install\schemas\attach_mysql_basic.sql ..\..\..\install\schemas\attach_mysql_basic.sql
copy attachment_mod\install\schemas\attach_mysql_schema.sql ..\..\..\install\schemas\attach_mysql_schema.sql
copy attachment_mod\install\schemas\attach_mssql_basic.sql ..\..\..\install\schemas\attach_mssql_basic.sql
copy attachment_mod\install\schemas\attach_mssql_schema.sql ..\..\..\install\schemas\attach_mssql_schema.sql
copy attachment_mod\install\schemas\attach_postgres_basic.sql ..\..\..\install\schemas\attach_postgres_basic.sql
copy attachment_mod\install\schemas\attach_postgres_schema.sql ..\..\..\install\schemas\attach_postgres_schema.sql
copy ..\..\..\common.php backups\common.php.txt
copy processed\common.php.txt ..\..\..\common.php
copy ..\..\..\faq.php backups\faq.php.txt
copy processed\faq.php.txt ..\..\..\faq.php
copy ..\..\..\modcp.php backups\modcp.php.txt
copy processed\modcp.php.txt ..\..\..\modcp.php
copy ..\..\..\posting.php backups\posting.php.txt
copy processed\posting.php.txt ..\..\..\posting.php
copy ..\..\..\privmsg.php backups\privmsg.php.txt
copy processed\privmsg.php.txt ..\..\..\privmsg.php
copy ..\..\..\viewforum.php backups\viewforum.php.txt
copy processed\viewforum.php.txt ..\..\..\viewforum.php
copy ..\..\..\viewtopic.php backups\viewtopic.php.txt
copy processed\viewtopic.php.txt ..\..\..\viewtopic.php
copy ..\..\..\admin\admin_forumauth.php backups\admin\admin_forumauth.php.txt
copy processed\admin\admin_forumauth.php.txt ..\..\..\admin\admin_forumauth.php
copy ..\..\..\admin\admin_forums.php backups\admin\admin_forums.php.txt
copy processed\admin\admin_forums.php.txt ..\..\..\admin\admin_forums.php
copy ..\..\..\admin\admin_groups.php backups\admin\admin_groups.php.txt
copy processed\admin\admin_groups.php.txt ..\..\..\admin\admin_groups.php
copy ..\..\..\admin\admin_ug_auth.php backups\admin\admin_ug_auth.php.txt
copy processed\admin\admin_ug_auth.php.txt ..\..\..\admin\admin_ug_auth.php
copy ..\..\..\admin\admin_users.php backups\admin\admin_users.php.txt
copy processed\admin\admin_users.php.txt ..\..\..\admin\admin_users.php
copy ..\..\..\includes\auth.php backups\includes\auth.php.txt
copy processed\includes\auth.php.txt ..\..\..\includes\auth.php
copy ..\..\..\includes\functions.php backups\includes\functions.php.txt
copy processed\includes\functions.php.txt ..\..\..\includes\functions.php
copy ..\..\..\includes\functions_admin.php backups\includes\functions_admin.php.txt
copy processed\includes\functions_admin.php.txt ..\..\..\includes\functions_admin.php
copy ..\..\..\includes\prune.php backups\includes\prune.php.txt
copy processed\includes\prune.php.txt ..\..\..\includes\prune.php
copy ..\..\..\includes\topic_review.php backups\includes\topic_review.php.txt
copy processed\includes\topic_review.php.txt ..\..\..\includes\topic_review.php
copy ..\..\..\includes\usercp_viewprofile.php backups\includes\usercp_viewprofile.php.txt
copy processed\includes\usercp_viewprofile.php.txt ..\..\..\includes\usercp_viewprofile.php
copy ..\..\..\templates\subSilver\modcp_body.tpl backups\templates\subSilver\modcp_body.tpl.txt
copy processed\templates\subSilver\modcp_body.tpl.txt ..\..\..\templates\subSilver\modcp_body.tpl
copy ..\..\..\templates\subSilver\posting_body.tpl backups\templates\subSilver\posting_body.tpl.txt
copy processed\templates\subSilver\posting_body.tpl.txt ..\..\..\templates\subSilver\posting_body.tpl
copy ..\..\..\templates\subSilver\posting_preview.tpl backups\templates\subSilver\posting_preview.tpl.txt
copy processed\templates\subSilver\posting_preview.tpl.txt ..\..\..\templates\subSilver\posting_preview.tpl
copy ..\..\..\templates\subSilver\posting_topic_review.tpl backups\templates\subSilver\posting_topic_review.tpl.txt
copy processed\templates\subSilver\posting_topic_review.tpl.txt ..\..\..\templates\subSilver\posting_topic_review.tpl
copy ..\..\..\templates\subSilver\privmsgs_body.tpl backups\templates\subSilver\privmsgs_body.tpl.txt
copy processed\templates\subSilver\privmsgs_body.tpl.txt ..\..\..\templates\subSilver\privmsgs_body.tpl
copy ..\..\..\templates\subSilver\privmsgs_preview.tpl backups\templates\subSilver\privmsgs_preview.tpl.txt
copy processed\templates\subSilver\privmsgs_preview.tpl.txt ..\..\..\templates\subSilver\privmsgs_preview.tpl
copy ..\..\..\templates\subSilver\privmsgs_read_body.tpl backups\templates\subSilver\privmsgs_read_body.tpl.txt
copy processed\templates\subSilver\privmsgs_read_body.tpl.txt ..\..\..\templates\subSilver\privmsgs_read_body.tpl
copy ..\..\..\templates\subSilver\profile_view_body.tpl backups\templates\subSilver\profile_view_body.tpl.txt
copy processed\templates\subSilver\profile_view_body.tpl.txt ..\..\..\templates\subSilver\profile_view_body.tpl
copy ..\..\..\templates\subSilver\viewforum_body.tpl backups\templates\subSilver\viewforum_body.tpl.txt
copy processed\templates\subSilver\viewforum_body.tpl.txt ..\..\..\templates\subSilver\viewforum_body.tpl
copy ..\..\..\templates\subSilver\viewtopic_body.tpl backups\templates\subSilver\viewtopic_body.tpl.txt
copy processed\templates\subSilver\viewtopic_body.tpl.txt ..\..\..\templates\subSilver\viewtopic_body.tpl
copy ..\..\..\templates\subSilver\admin\group_edit_body.tpl backups\templates\subSilver\admin\group_edit_body.tpl.txt
copy processed\templates\subSilver\admin\group_edit_body.tpl.txt ..\..\..\templates\subSilver\admin\group_edit_body.tpl
copy ..\..\..\templates\subSilver\admin\user_edit_body.tpl backups\templates\subSilver\admin\user_edit_body.tpl.txt
copy processed\templates\subSilver\admin\user_edit_body.tpl.txt ..\..\..\templates\subSilver\admin\user_edit_body.tpl
