cp attachment_mod/download.php ../../../download.php
cp attachment_mod/uacp.php ../../../uacp.php
cp attachment_mod/attach_rules.php ../../../attach_rules.php
cp attachment_mod/admin/admin_attach_cp.php ../../../admin/admin_attach_cp.php
cp attachment_mod/admin/admin_attachments.php ../../../admin/admin_attachments.php
cp attachment_mod/admin/admin_extensions.php ../../../admin/admin_extensions.php
cp attachment_mod/attach_mod/attachment_mod.php ../../../attach_mod/attachment_mod.php
cp attachment_mod/attach_mod/displaying.php ../../../attach_mod/displaying.php
cp attachment_mod/attach_mod/index.htm ../../../attach_mod/index.htm
cp attachment_mod/attach_mod/pm_attachments.php ../../../attach_mod/pm_attachments.php
cp attachment_mod/attach_mod/posting_attachments.php ../../../attach_mod/posting_attachments.php
cp attachment_mod/attach_mod/includes/constants.php ../../../attach_mod/includes/constants.php
cp attachment_mod/attach_mod/includes/functions_admin.php ../../../attach_mod/includes/functions_admin.php
cp attachment_mod/attach_mod/includes/functions_attach.php ../../../attach_mod/includes/functions_attach.php
cp attachment_mod/attach_mod/includes/functions_delete.php ../../../attach_mod/includes/functions_delete.php
cp attachment_mod/attach_mod/includes/functions_filetypes.php ../../../attach_mod/includes/functions_filetypes.php
cp attachment_mod/attach_mod/includes/functions_includes.php ../../../attach_mod/includes/functions_includes.php
cp attachment_mod/attach_mod/includes/functions_selects.php ../../../attach_mod/includes/functions_selects.php
cp attachment_mod/attach_mod/includes/functions_thumbs.php ../../../attach_mod/includes/functions_thumbs.php
cp attachment_mod/attach_mod/includes/index.htm ../../../attach_mod/includes/index.htm
cp attachment_mod/files/index.php ../../../files/index.php
cp attachment_mod/images/icon_clip.gif ../../../images/icon_clip.gif
cp attachment_mod/images/icon_disk.gif ../../../images/icon_disk.gif
cp attachment_mod/images/icon_disk_gray.gif ../../../images/icon_disk_gray.gif
cp attachment_mod/templates/subSilver/add_attachment_body.tpl ../../../templates/subSilver/add_attachment_body.tpl
cp attachment_mod/templates/subSilver/posted_attachments_body.tpl ../../../templates/subSilver/posted_attachments_body.tpl
cp attachment_mod/templates/subSilver/posting_attach_body.tpl ../../../templates/subSilver/posting_attach_body.tpl
cp attachment_mod/templates/subSilver/posting_attach_rules.tpl ../../../templates/subSilver/posting_attach_rules.tpl
cp attachment_mod/templates/subSilver/uacp_body.tpl ../../../templates/subSilver/uacp_body.tpl
cp attachment_mod/templates/subSilver/viewtopic_attach_body.tpl ../../../templates/subSilver/viewtopic_attach_body.tpl
cp attachment_mod/templates/subSilver/admin/attach_cat_body.tpl ../../../templates/subSilver/admin/attach_cat_body.tpl
cp attachment_mod/templates/subSilver/admin/attach_cp_attachments.tpl ../../../templates/subSilver/admin/attach_cp_attachments.tpl
cp attachment_mod/templates/subSilver/admin/attach_cp_body.tpl ../../../templates/subSilver/admin/attach_cp_body.tpl
cp attachment_mod/templates/subSilver/admin/attach_cp_search.tpl ../../../templates/subSilver/admin/attach_cp_search.tpl
cp attachment_mod/templates/subSilver/admin/attach_cp_user.tpl ../../../templates/subSilver/admin/attach_cp_user.tpl
cp attachment_mod/templates/subSilver/admin/attach_extension_groups.tpl ../../../templates/subSilver/admin/attach_extension_groups.tpl
cp attachment_mod/templates/subSilver/admin/attach_extensions.tpl ../../../templates/subSilver/admin/attach_extensions.tpl
cp attachment_mod/templates/subSilver/admin/attach_forbidden_extensions.tpl ../../../templates/subSilver/admin/attach_forbidden_extensions.tpl
cp attachment_mod/templates/subSilver/admin/attach_manage_body.tpl ../../../templates/subSilver/admin/attach_manage_body.tpl
cp attachment_mod/templates/subSilver/admin/attach_quota_body.tpl ../../../templates/subSilver/admin/attach_quota_body.tpl
cp attachment_mod/templates/subSilver/admin/attach_shadow.tpl ../../../templates/subSilver/admin/attach_shadow.tpl
cp attachment_mod/templates/subSilver/admin/extension_groups_permissions.tpl ../../../templates/subSilver/admin/extension_groups_permissions.tpl
cp attachment_mod/language/lang_english/lang_admin_attach.php ../../../language/lang_english/lang_admin_attach.php
cp attachment_mod/language/lang_english/lang_admin_attach.php ../../../language/lang_russian/lang_admin_attach.php
cp attachment_mod/language/lang_english/lang_faq_attach.php ../../../language/lang_english/lang_faq_attach.php
cp attachment_mod/language/lang_english/lang_faq_attach.php ../../../language/lang_russian/lang_faq_attach.php
cp attachment_mod/language/lang_english/lang_main_attach.php ../../../language/lang_english/lang_main_attach.php
cp attachment_mod/language/lang_english/lang_main_attach.php ../../../language/lang_russian/lang_main_attach.php
cp attachment_mod/install/install.php ../../../install/install.php
cp attachment_mod/install/schemas/attach_mysql_basic.sql ../../../install/schemas/attach_mysql_basic.sql
cp attachment_mod/install/schemas/attach_mysql_schema.sql ../../../install/schemas/attach_mysql_schema.sql
cp attachment_mod/install/schemas/attach_mssql_basic.sql ../../../install/schemas/attach_mssql_basic.sql
cp attachment_mod/install/schemas/attach_mssql_schema.sql ../../../install/schemas/attach_mssql_schema.sql
cp attachment_mod/install/schemas/attach_postgres_basic.sql ../../../install/schemas/attach_postgres_basic.sql
cp attachment_mod/install/schemas/attach_postgres_schema.sql ../../../install/schemas/attach_postgres_schema.sql
cp ../../../common.php backups/common.php.txt
cp processed/common.php.txt ../../../common.php
cp ../../../faq.php backups/faq.php.txt
cp processed/faq.php.txt ../../../faq.php
cp ../../../modcp.php backups/modcp.php.txt
cp processed/modcp.php.txt ../../../modcp.php
cp ../../../posting.php backups/posting.php.txt
cp processed/posting.php.txt ../../../posting.php
cp ../../../privmsg.php backups/privmsg.php.txt
cp processed/privmsg.php.txt ../../../privmsg.php
cp ../../../viewforum.php backups/viewforum.php.txt
cp processed/viewforum.php.txt ../../../viewforum.php
cp ../../../viewtopic.php backups/viewtopic.php.txt
cp processed/viewtopic.php.txt ../../../viewtopic.php
cp ../../../admin/admin_forumauth.php backups/admin/admin_forumauth.php.txt
cp processed/admin/admin_forumauth.php.txt ../../../admin/admin_forumauth.php
cp ../../../admin/admin_forums.php backups/admin/admin_forums.php.txt
cp processed/admin/admin_forums.php.txt ../../../admin/admin_forums.php
cp ../../../admin/admin_groups.php backups/admin/admin_groups.php.txt
cp processed/admin/admin_groups.php.txt ../../../admin/admin_groups.php
cp ../../../admin/admin_ug_auth.php backups/admin/admin_ug_auth.php.txt
cp processed/admin/admin_ug_auth.php.txt ../../../admin/admin_ug_auth.php
cp ../../../admin/admin_users.php backups/admin/admin_users.php.txt
cp processed/admin/admin_users.php.txt ../../../admin/admin_users.php
cp ../../../includes/auth.php backups/includes/auth.php.txt
cp processed/includes/auth.php.txt ../../../includes/auth.php
cp ../../../includes/functions.php backups/includes/functions.php.txt
cp processed/includes/functions.php.txt ../../../includes/functions.php
cp ../../../includes/functions_admin.php backups/includes/functions_admin.php.txt
cp processed/includes/functions_admin.php.txt ../../../includes/functions_admin.php
cp ../../../includes/prune.php backups/includes/prune.php.txt
cp processed/includes/prune.php.txt ../../../includes/prune.php
cp ../../../includes/topic_review.php backups/includes/topic_review.php.txt
cp processed/includes/topic_review.php.txt ../../../includes/topic_review.php
cp ../../../includes/usercp_viewprofile.php backups/includes/usercp_viewprofile.php.txt
cp processed/includes/usercp_viewprofile.php.txt ../../../includes/usercp_viewprofile.php
cp ../../../templates/subSilver/modcp_body.tpl backups/templates/subSilver/modcp_body.tpl.txt
cp processed/templates/subSilver/modcp_body.tpl.txt ../../../templates/subSilver/modcp_body.tpl
cp ../../../templates/subSilver/posting_body.tpl backups/templates/subSilver/posting_body.tpl.txt
cp processed/templates/subSilver/posting_body.tpl.txt ../../../templates/subSilver/posting_body.tpl
cp ../../../templates/subSilver/posting_preview.tpl backups/templates/subSilver/posting_preview.tpl.txt
cp processed/templates/subSilver/posting_preview.tpl.txt ../../../templates/subSilver/posting_preview.tpl
cp ../../../templates/subSilver/posting_topic_review.tpl backups/templates/subSilver/posting_topic_review.tpl.txt
cp processed/templates/subSilver/posting_topic_review.tpl.txt ../../../templates/subSilver/posting_topic_review.tpl
cp ../../../templates/subSilver/privmsgs_body.tpl backups/templates/subSilver/privmsgs_body.tpl.txt
cp processed/templates/subSilver/privmsgs_body.tpl.txt ../../../templates/subSilver/privmsgs_body.tpl
cp ../../../templates/subSilver/privmsgs_preview.tpl backups/templates/subSilver/privmsgs_preview.tpl.txt
cp processed/templates/subSilver/privmsgs_preview.tpl.txt ../../../templates/subSilver/privmsgs_preview.tpl
cp ../../../templates/subSilver/privmsgs_read_body.tpl backups/templates/subSilver/privmsgs_read_body.tpl.txt
cp processed/templates/subSilver/privmsgs_read_body.tpl.txt ../../../templates/subSilver/privmsgs_read_body.tpl
cp ../../../templates/subSilver/profile_view_body.tpl backups/templates/subSilver/profile_view_body.tpl.txt
cp processed/templates/subSilver/profile_view_body.tpl.txt ../../../templates/subSilver/profile_view_body.tpl
cp ../../../templates/subSilver/viewforum_body.tpl backups/templates/subSilver/viewforum_body.tpl.txt
cp processed/templates/subSilver/viewforum_body.tpl.txt ../../../templates/subSilver/viewforum_body.tpl
cp ../../../templates/subSilver/viewtopic_body.tpl backups/templates/subSilver/viewtopic_body.tpl.txt
cp processed/templates/subSilver/viewtopic_body.tpl.txt ../../../templates/subSilver/viewtopic_body.tpl
cp ../../../templates/subSilver/admin/group_edit_body.tpl backups/templates/subSilver/admin/group_edit_body.tpl.txt
cp processed/templates/subSilver/admin/group_edit_body.tpl.txt ../../../templates/subSilver/admin/group_edit_body.tpl
cp ../../../templates/subSilver/admin/user_edit_body.tpl backups/templates/subSilver/admin/user_edit_body.tpl.txt
cp processed/templates/subSilver/admin/user_edit_body.tpl.txt ../../../templates/subSilver/admin/user_edit_body.tpl
