cp root/admin/admin_logs.php ../../../admin/admin_logs.php
cp root/admin/admin_logs_config.php ../../../admin/admin_logs_config.php
cp root/includes/functions_log.php ../../../includes/functions_log.php
cp root/includes/rules.php ../../../includes/rules.php
cp root/templates/subSilver/rules_body.tpl ../../../templates/subSilver/rules_body.tpl
cp root/templates/subSilver/admin/logs_body.tpl ../../../templates/subSilver/admin/logs_body.tpl
cp root/templates/subSilver/admin/logs_config_body.tpl ../../../templates/subSilver/admin/logs_config_body.tpl
cp ../../../modcp.php backups/modcp.php.txt
cp processed/modcp.php.txt ../../../modcp.php
cp ../../../posting.php backups/posting.php.txt
cp processed/posting.php.txt ../../../posting.php
cp ../../../includes/constants.php backups/includes/constants.php.txt
cp processed/includes/constants.php.txt ../../../includes/constants.php
cp ../../../language/lang_english/lang_admin.php backups/language/lang_english/lang_admin.php.txt
cp processed/language/lang_english/lang_admin.php.txt ../../../language/lang_english/lang_admin.php
cp ../../../language/lang_russian/lang_admin.php backups/language/lang_russian/lang_admin.php.txt
cp processed/language/lang_russian/lang_admin.php.txt ../../../language/lang_russian/lang_admin.php
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
cp ../../../language/lang_russian/lang_main.php backups/language/lang_russian/lang_main.php.txt
cp processed/language/lang_russian/lang_main.php.txt ../../../language/lang_russian/lang_main.php
cp log_actions_db_update.php ../../../log_actions_db_update.php
