copy root\admin\admin_logs.php ..\..\..\admin\admin_logs.php
copy root\admin\admin_logs_config.php ..\..\..\admin\admin_logs_config.php
copy root\includes\functions_log.php ..\..\..\includes\functions_log.php
copy root\includes\rules.php ..\..\..\includes\rules.php
copy root\templates\subSilver\rules_body.tpl ..\..\..\templates\subSilver\rules_body.tpl
copy root\templates\subSilver\admin\logs_body.tpl ..\..\..\templates\subSilver\admin\logs_body.tpl
copy root\templates\subSilver\admin\logs_config_body.tpl ..\..\..\templates\subSilver\admin\logs_config_body.tpl
copy ..\..\..\modcp.php backups\modcp.php.txt
copy processed\modcp.php.txt ..\..\..\modcp.php
copy ..\..\..\posting.php backups\posting.php.txt
copy processed\posting.php.txt ..\..\..\posting.php
copy ..\..\..\includes\constants.php backups\includes\constants.php.txt
copy processed\includes\constants.php.txt ..\..\..\includes\constants.php
copy ..\..\..\language\lang_english\lang_admin.php backups\language\lang_english\lang_admin.php.txt
copy processed\language\lang_english\lang_admin.php.txt ..\..\..\language\lang_english\lang_admin.php
copy ..\..\..\language\lang_russian\lang_admin.php backups\language\lang_russian\lang_admin.php.txt
copy processed\language\lang_russian\lang_admin.php.txt ..\..\..\language\lang_russian\lang_admin.php
copy ..\..\..\language\lang_english\lang_main.php backups\language\lang_english\lang_main.php.txt
copy processed\language\lang_english\lang_main.php.txt ..\..\..\language\lang_english\lang_main.php
copy ..\..\..\language\lang_russian\lang_main.php backups\language\lang_russian\lang_main.php.txt
copy processed\language\lang_russian\lang_main.php.txt ..\..\..\language\lang_russian\lang_main.php
copy log_actions_db_update.php ..\..\..\log_actions_db_update.php
