cp ../../../posting.php backups/posting.php.txt
cp processed/posting.php.txt ../../../posting.php
cp ../../../language/lang_russian/lang_main.php backups/language/lang_russian/lang_main.php.txt
cp processed/language/lang_russian/lang_main.php.txt ../../../language/lang_russian/lang_main.php
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
cp ../../../language/lang_russian/lang_main.php backups/language/lang_russian/lang_main.php.txt
cp processed/language/lang_russian/lang_main.php.txt ../../../language/lang_russian/lang_main.php
cp ../../../templates/subSilver/posting_body.tpl backups/templates/subSilver/posting_body.tpl.txt
cp processed/templates/subSilver/posting_body.tpl.txt ../../../templates/subSilver/posting_body.tpl
