copy root\includes\functions_usergroup.php ..\..\..\includes\functions_usergroup.php
copy root\templates\subSilver\show_usergroup.tpl ..\..\..\templates\subSilver\show_usergroup.tpl
copy root\templates\subSilver\show_usergroup_image_only.tpl ..\..\..\templates\subSilver\show_usergroup_image_only.tpl
copy root\templates\subSilver\show_usergroup_as_dropdown.tpl ..\..\..\templates\subSilver\show_usergroup_as_dropdown.tpl
copy root\templates\subSilver\images\groups_diamond3.gif ..\..\..\templates\subSilver\images\groups_diamond3.gif
copy root\templates\subSilver\images\groups_snow.gif ..\..\..\templates\subSilver\images\groups_snow.gif
copy root\templates\subSilver\images\groups_star2.gif ..\..\..\templates\subSilver\images\groups_star2.gif
copy ..\..\..\viewtopic.php backups\viewtopic.php.txt
copy processed\viewtopic.php.txt ..\..\..\viewtopic.php
copy ..\..\..\includes\template.php backups\includes\template.php.txt
copy processed\includes\template.php.txt ..\..\..\includes\template.php
copy ..\..\..\includes\usercp_viewprofile.php backups\includes\usercp_viewprofile.php.txt
copy processed\includes\usercp_viewprofile.php.txt ..\..\..\includes\usercp_viewprofile.php
copy ..\..\..\templates\subSilver\profile_view_body.tpl backups\templates\subSilver\profile_view_body.tpl.txt
copy processed\templates\subSilver\profile_view_body.tpl.txt ..\..\..\templates\subSilver\profile_view_body.tpl
copy ..\..\..\templates\subSilver\subSilver.cfg backups\templates\subSilver\subSilver.cfg.txt
copy processed\templates\subSilver\subSilver.cfg.txt ..\..\..\templates\subSilver\subSilver.cfg
copy ..\..\..\templates\subSilver\viewtopic_body.tpl backups\templates\subSilver\viewtopic_body.tpl.txt
copy processed\templates\subSilver\viewtopic_body.tpl.txt ..\..\..\templates\subSilver\viewtopic_body.tpl
