cp root/includes/functions_usergroup.php ../../../includes/functions_usergroup.php
cp root/templates/subSilver/show_usergroup.tpl ../../../templates/subSilver/show_usergroup.tpl
cp root/templates/subSilver/show_usergroup_image_only.tpl ../../../templates/subSilver/show_usergroup_image_only.tpl
cp root/templates/subSilver/show_usergroup_as_dropdown.tpl ../../../templates/subSilver/show_usergroup_as_dropdown.tpl
cp root/templates/subSilver/images/groups_diamond3.gif ../../../templates/subSilver/images/groups_diamond3.gif
cp root/templates/subSilver/images/groups_snow.gif ../../../templates/subSilver/images/groups_snow.gif
cp root/templates/subSilver/images/groups_star2.gif ../../../templates/subSilver/images/groups_star2.gif
cp ../../../viewtopic.php backups/viewtopic.php.txt
cp processed/viewtopic.php.txt ../../../viewtopic.php
cp ../../../includes/template.php backups/includes/template.php.txt
cp processed/includes/template.php.txt ../../../includes/template.php
cp ../../../includes/usercp_viewprofile.php backups/includes/usercp_viewprofile.php.txt
cp processed/includes/usercp_viewprofile.php.txt ../../../includes/usercp_viewprofile.php
cp ../../../templates/subSilver/profile_view_body.tpl backups/templates/subSilver/profile_view_body.tpl.txt
cp processed/templates/subSilver/profile_view_body.tpl.txt ../../../templates/subSilver/profile_view_body.tpl
cp ../../../templates/subSilver/subSilver.cfg backups/templates/subSilver/subSilver.cfg.txt
cp processed/templates/subSilver/subSilver.cfg.txt ../../../templates/subSilver/subSilver.cfg
cp ../../../templates/subSilver/viewtopic_body.tpl backups/templates/subSilver/viewtopic_body.tpl.txt
cp processed/templates/subSilver/viewtopic_body.tpl.txt ../../../templates/subSilver/viewtopic_body.tpl
