copy global_announcement_db_update.php ..\..\..\global_announcement_db_update.php
copy root\templates\subSilver\images\folder_global_announce.gif ..\..\..\templates\subSilver\images\folder_global_announce.gif
copy root\templates\subSilver\images\folder_global_announce_new.gif ..\..\..\templates\subSilver\images\folder_global_announce_new.gif
copy ..\..\..\index.php backups\index.php.txt
copy processed\index.php.txt ..\..\..\index.php
copy ..\..\..\modcp.php backups\modcp.php.txt
copy processed\modcp.php.txt ..\..\..\modcp.php
copy ..\..\..\posting.php backups\posting.php.txt
copy processed\posting.php.txt ..\..\..\posting.php
copy ..\..\..\search.php backups\search.php.txt
copy processed\search.php.txt ..\..\..\search.php
copy ..\..\..\viewforum.php backups\viewforum.php.txt
copy processed\viewforum.php.txt ..\..\..\viewforum.php
copy ..\..\..\admin\admin_forumauth.php backups\admin\admin_forumauth.php.txt
copy processed\admin\admin_forumauth.php.txt ..\..\..\admin\admin_forumauth.php
copy ..\..\..\admin\admin_ug_auth.php backups\admin\admin_ug_auth.php.txt
copy processed\admin\admin_ug_auth.php.txt ..\..\..\admin\admin_ug_auth.php
copy ..\..\..\includes\auth.php backups\includes\auth.php.txt
copy processed\includes\auth.php.txt ..\..\..\includes\auth.php
copy ..\..\..\includes\constants.php backups\includes\constants.php.txt
copy processed\includes\constants.php.txt ..\..\..\includes\constants.php
copy ..\..\..\includes\functions.php backups\includes\functions.php.txt
copy processed\includes\functions.php.txt ..\..\..\includes\functions.php
copy ..\..\..\language\lang_english\lang_admin.php backups\language\lang_english\lang_admin.php.txt
copy processed\language\lang_english\lang_admin.php.txt ..\..\..\language\lang_english\lang_admin.php
copy ..\..\..\language\lang_russian\lang_admin.php backups\language\lang_russian\lang_admin.php.txt
copy processed\language\lang_russian\lang_admin.php.txt ..\..\..\language\lang_russian\lang_admin.php
copy ..\..\..\language\lang_english\lang_main.php backups\language\lang_english\lang_main.php.txt
copy processed\language\lang_english\lang_main.php.txt ..\..\..\language\lang_english\lang_main.php
copy ..\..\..\language\lang_russian\lang_main.php backups\language\lang_russian\lang_main.php.txt
copy processed\language\lang_russian\lang_main.php.txt ..\..\..\language\lang_russian\lang_main.php
copy ..\..\..\templates\subSilver\subSilver.cfg backups\templates\subSilver\subSilver.cfg.txt
copy processed\templates\subSilver\subSilver.cfg.txt ..\..\..\templates\subSilver\subSilver.cfg
copy ..\..\..\templates\subSilver\viewforum_body.tpl backups\templates\subSilver\viewforum_body.tpl.txt
copy processed\templates\subSilver\viewforum_body.tpl.txt ..\..\..\templates\subSilver\viewforum_body.tpl
