cp global_announcement_db_update.php ../../../global_announcement_db_update.php
cp root/templates/subSilver/images/folder_global_announce.gif ../../../templates/subSilver/images/folder_global_announce.gif
cp root/templates/subSilver/images/folder_global_announce_new.gif ../../../templates/subSilver/images/folder_global_announce_new.gif
cp ../../../index.php backups/index.php.txt
cp processed/index.php.txt ../../../index.php
cp ../../../modcp.php backups/modcp.php.txt
cp processed/modcp.php.txt ../../../modcp.php
cp ../../../posting.php backups/posting.php.txt
cp processed/posting.php.txt ../../../posting.php
cp ../../../search.php backups/search.php.txt
cp processed/search.php.txt ../../../search.php
cp ../../../viewforum.php backups/viewforum.php.txt
cp processed/viewforum.php.txt ../../../viewforum.php
cp ../../../admin/admin_forumauth.php backups/admin/admin_forumauth.php.txt
cp processed/admin/admin_forumauth.php.txt ../../../admin/admin_forumauth.php
cp ../../../admin/admin_ug_auth.php backups/admin/admin_ug_auth.php.txt
cp processed/admin/admin_ug_auth.php.txt ../../../admin/admin_ug_auth.php
cp ../../../includes/auth.php backups/includes/auth.php.txt
cp processed/includes/auth.php.txt ../../../includes/auth.php
cp ../../../includes/constants.php backups/includes/constants.php.txt
cp processed/includes/constants.php.txt ../../../includes/constants.php
cp ../../../includes/functions.php backups/includes/functions.php.txt
cp processed/includes/functions.php.txt ../../../includes/functions.php
cp ../../../language/lang_english/lang_admin.php backups/language/lang_english/lang_admin.php.txt
cp processed/language/lang_english/lang_admin.php.txt ../../../language/lang_english/lang_admin.php
cp ../../../language/lang_russian/lang_admin.php backups/language/lang_russian/lang_admin.php.txt
cp processed/language/lang_russian/lang_admin.php.txt ../../../language/lang_russian/lang_admin.php
cp ../../../language/lang_english/lang_main.php backups/language/lang_english/lang_main.php.txt
cp processed/language/lang_english/lang_main.php.txt ../../../language/lang_english/lang_main.php
cp ../../../language/lang_russian/lang_main.php backups/language/lang_russian/lang_main.php.txt
cp processed/language/lang_russian/lang_main.php.txt ../../../language/lang_russian/lang_main.php
cp ../../../templates/subSilver/subSilver.cfg backups/templates/subSilver/subSilver.cfg.txt
cp processed/templates/subSilver/subSilver.cfg.txt ../../../templates/subSilver/subSilver.cfg
cp ../../../templates/subSilver/viewforum_body.tpl backups/templates/subSilver/viewforum_body.tpl.txt
cp processed/templates/subSilver/viewforum_body.tpl.txt ../../../templates/subSilver/viewforum_body.tpl
